analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 1
  lightness: 1
  brandStrength: 0.5966111517045647
  brandColors:
    - '#CCCCCC'
    - '#FFFFFF'
  rhythmicContrast: 0
typography_spectrum: 0.702509
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0
favicon: null
name: Weld
