favicon: null
cta:
  bucket: null
  version: null
  domain: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 1
  brandStrength: 0.5966111517045647
  rhythmicContrast: 0
  brandColors:
    - '#CCCCCC'
    - '#FFFFFF'
  lightness: 1
typography_spectrum: 0.7706093
layout_spectrum: 0
analytics:
  twitter: null
  google: null
  facebook: null
name: Weld
